#!/usr/bin/env python3
"""
Unsloth SFT Trainer integration for the data flywheel.

Reads training_dataset.jsonl from the project-local data pipeline output,
converts to Alpaca format, and launches Unsloth fine-tuning.

Usage:
    python unsloth_trainer.py --config config.yaml
    python unsloth_trainer.py --model unsloth/llama-3-8b --epochs 3 --data ../data/outputs/langfuse_pipeline/training_dataset.jsonl
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

TRAINING_DIR = Path(__file__).resolve().parent
FLYWHEEL_ROOT = TRAINING_DIR.parent
DEFAULT_TRAINING_DATASET = FLYWHEEL_ROOT / "data" / "outputs" / "langfuse_pipeline" / "training_dataset.jsonl"
RUNS_DIR = TRAINING_DIR / "runs"
RUNS_DIR.mkdir(exist_ok=True)


def load_training_data(jsonl_path: Path) -> list[dict]:
    """Load training examples from JSONL file produced by Langfuse pipeline."""
    examples = []
    with jsonl_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                examples.append(json.loads(line))
    return examples


def convert_to_alpaca(examples: list[dict]) -> list[dict]:
    """Convert internal training examples to Alpaca format for Unsloth."""
    alpaca = []
    for ex in examples:
        instruction = ex.get("input", "").strip()
        output = ex.get("output", "").strip()
        if not instruction or not output:
            continue
        labels = ex.get("labels", {})
        parts = []
        if labels.get("correctness"):
            parts.append(f"Quality: {labels['correctness']}")
        if labels.get("comment"):
            parts.append(f"Note: {labels['comment']}")
        context = "\n".join(parts)
        text = f"### Instruction:\n{instruction}\n\n### Context:\n{context}\n\n### Response:\n{output}" if context else f"### Instruction:\n{instruction}\n\n### Response:\n{output}"
        alpaca.append({
            "instruction": instruction,
            "input": context,
            "output": output,
            "text": text,
        })
    return alpaca


def save_alpaca_dataset(alpaca_data: list[dict], output_path: Path) -> Path:
    """Save as JSON dataset for Unsloth."""
    output_path.write_text(
        json.dumps(alpaca_data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    return output_path


def record_run(run_info: dict) -> Path:
    """Record training run metadata."""
    run_id = datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S")
    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    run_info["run_id"] = run_id
    run_info["recorded_at"] = datetime.now(timezone.utc).isoformat()

    meta_path = run_dir / "run.json"
    meta_path.write_text(
        json.dumps(run_info, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    runs_index = RUNS_DIR / "index.json"
    index = []
    if runs_index.exists():
        index = json.loads(runs_index.read_text(encoding="utf-8"))
    index.append({
        "run_id": run_id,
        "timestamp": run_info["recorded_at"],
        "model": run_info.get("model", "unknown"),
        "status": run_info.get("status", "unknown"),
        "metrics": run_info.get("metrics", {}),
    })
    index.sort(key=lambda x: x["timestamp"], reverse=True)
    runs_index.write_text(
        json.dumps(index, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    return meta_path


def _build_training_script(dataset_path: Path, model_name: str, output_dir: Path, config: dict) -> str:
    """生成独立的 Unsloth 训练 Python 脚本（替代不存在的 unsloth-cli）。

    P1 修复：原实现依赖 `unsloth-cli` 命令（官方并不存在），改为生成标准
    `FastLanguageModel + SFTTrainer` 训练脚本，由 subprocess.run([sys.executable, script]) 执行。
    """
    max_seq_length = config.get("max_seq_length", 2048)
    load_in_4bit = config.get("load_in_4bit", True)
    lora_r = config.get("lora_r", 16)
    lora_alpha = config.get("lora_alpha", 32)
    num_epochs = config.get("num_epochs", 3)
    learning_rate = config.get("learning_rate", 2e-4)
    batch_size = config.get("batch_size", 2)
    training_type = config.get("training_type", "lora")

    # 注意：外层 f-string 中，生成脚本里的 f-string 字面量 {VAR} 需写成 {{VAR}}
    return f'''#!/usr/bin/env python3
"""Auto-generated by unsloth_trainer.py - runs Unsloth SFT on the prepared Alpaca dataset."""
import json
import torch
from datasets import Dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig

DATASET_PATH = {str(dataset_path)!r}
MODEL_NAME = {model_name!r}
OUTPUT_DIR = {str(output_dir)!r}
MAX_SEQ_LENGTH = {max_seq_length}
LOAD_IN_4BIT = {load_in_4bit}
LORA_R = {lora_r}
LORA_ALPHA = {lora_alpha}
NUM_EPOCHS = {num_epochs}
LEARNING_RATE = {learning_rate}
BATCH_SIZE = {batch_size}
TRAINING_TYPE = {training_type!r}


def main():
    print(f"[unsloth] Loading model {{MODEL_NAME}} (4bit={{LOAD_IN_4BIT}})...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=LOAD_IN_4BIT,
    )

    if TRAINING_TYPE == "lora":
        model = FastLanguageModel.get_peft_model(
            model,
            r=LORA_R,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            lora_alpha=LORA_ALPHA,
            lora_dropout=0,
            bias="none",
            use_gradient_checkpointing="unsloth",
            random_state=3407,
            use_rslora=False,
            loftq_config=None,
        )

    print(f"[unsloth] Loading dataset from {{DATASET_PATH}}...")
    raw = json.loads(open(DATASET_PATH, encoding="utf-8").read())
    dataset = Dataset.from_list(raw)
    print(f"[unsloth] Dataset size: {{len(dataset)}}")

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        args=SFTConfig(
            per_device_train_batch_size=BATCH_SIZE,
            gradient_accumulation_steps=4,
            num_train_epochs=NUM_EPOCHS,
            warmup_ratio=0.03,
            learning_rate=LEARNING_RATE,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            seed=3407,
            output_dir=OUTPUT_DIR,
            report_to="none",
        ),
    )
    print("[unsloth] Starting training...")
    trainer.train()
    print(f"[unsloth] Saving model to {{OUTPUT_DIR}}...")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print("[unsloth] Done.")


if __name__ == "__main__":
    main()
'''


def run_unsloth_training(dataset_path: Path, config: dict) -> dict:
    """生成 Unsloth 训练脚本并通过 subprocess 执行。

    P1 修复：原实现用 os.system(拼接字符串) + 依赖不存在的 unsloth-cli；
    改为 subprocess.run([sys.executable, script]) 执行生成的 Python 脚本。
    """
    model_name = config.get("model_name", "unsloth/llama-3-8b")
    output_dir = TRAINING_DIR / "runs" / datetime.now(timezone.utc).strftime("%Y-%m-%d_%H-%M-%S") / "model"
    output_dir.mkdir(parents=True, exist_ok=True)

    script_path = output_dir.parent / "train_unsloth.py"
    script_content = _build_training_script(dataset_path, model_name, output_dir, config)
    script_path.write_text(script_content, encoding="utf-8")

    cmd = [sys.executable, str(script_path)]

    run_info = {
        "model": model_name,
        "command": " ".join(cmd),
        "dataset_path": str(dataset_path),
        "config": config,
        "output_dir": str(output_dir),
        "script_path": str(script_path),
        "status": "pending",
        "metrics": {},
    }

    if config.get("dry_run"):
        print(f"[DRY RUN] Would execute: {' '.join(cmd)}")
        print(f"[DRY RUN] Training script written to: {script_path}")
        run_info["status"] = "dry_run"
        record_run(run_info)
        return run_info

    print(f"Starting Unsloth training...")
    print(f"Command: {' '.join(cmd)}")
    print(f"Script: {script_path}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print(result.stderr, file=sys.stderr)
        if result.returncode == 0:
            run_info["status"] = "completed"
        else:
            run_info["status"] = "failed"
            run_info["exit_code"] = result.returncode
            run_info["stderr"] = result.stderr[-2000:] if result.stderr else ""
    except FileNotFoundError as e:
        run_info["status"] = "failed"
        run_info["error"] = str(e)

    record_run(run_info)
    return run_info


def main():
    parser = argparse.ArgumentParser(description="Unsloth Trainer for Data Flywheel")
    parser.add_argument("--data", type=str, default=None,
                        help="Path to training_dataset.jsonl")
    parser.add_argument("--config", type=str, default=None,
                        help="Path to training config YAML/JSON")
    parser.add_argument("--model", type=str, default="unsloth/llama-3-8b")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-4)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--lora-r", type=int, default=16)
    parser.add_argument("--training-type", type=str, default="lora")
    parser.add_argument("--max-seq-length", type=int, default=2048)
    parser.add_argument("--load-in-4bit", action="store_true", default=True)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--list-runs", action="store_true", help="List all training runs")

    args = parser.parse_args()

    if args.list_runs:
        index_path = RUNS_DIR / "index.json"
        if index_path.exists():
            index = json.loads(index_path.read_text(encoding="utf-8"))
            for run in index:
                print(f"  {run['run_id']}  {run['model']}  {run['status']}  {run['metrics']}")
        else:
            print("No training runs recorded.")
        return

    config = {}
    if args.config:
        config_path = Path(args.config)
        if config_path.suffix in (".yaml", ".yml"):
            import yaml
            config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
        else:
            config = json.loads(config_path.read_text(encoding="utf-8"))

    config.setdefault("model_name", args.model)
    config.setdefault("num_epochs", args.epochs)
    config.setdefault("learning_rate", args.lr)
    config.setdefault("batch_size", args.batch_size)
    config.setdefault("lora_r", args.lora_r)
    config.setdefault("training_type", args.training_type)
    config.setdefault("max_seq_length", args.max_seq_length)
    config.setdefault("load_in_4bit", args.load_in_4bit)
    config.setdefault("dry_run", args.dry_run)

    data_path = Path(args.data) if args.data else DEFAULT_TRAINING_DATASET

    if not data_path.exists():
        print(f"Training data not found: {data_path}")
        print("Run the project import pipeline, then generate the training dataset package.")
        sys.exit(1)

    examples = load_training_data(data_path)
    print(f"Loaded {len(examples)} training examples")

    alpaca_data = convert_to_alpaca(examples)
    print(f"Converted {len(alpaca_data)} examples to Alpaca format")

    dataset_path = TRAINING_DIR / "alpaca_dataset.json"
    save_alpaca_dataset(alpaca_data, dataset_path)
    print(f"Saved Alpaca dataset to {dataset_path}")

    result = run_unsloth_training(dataset_path, config)
    print(f"\nTraining run recorded: {result.get('run_id', 'N/A')}")
    print(f"Status: {result['status']}")


if __name__ == "__main__":
    main()
