#!/usr/bin/env python3
"""Auto-generated by unsloth_trainer.py - runs Unsloth SFT on the prepared Alpaca dataset."""
import json
import torch
from datasets import Dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer, SFTConfig

DATASET_PATH = 'training/alpaca_dataset.json'
MODEL_NAME = 'unsloth/llama-3-8b'
OUTPUT_DIR = 'training/runs/2026-08-10_09-12-18/model'
MAX_SEQ_LENGTH = 2048
LOAD_IN_4BIT = True
LORA_R = 16
LORA_ALPHA = 32
NUM_EPOCHS = 3
LEARNING_RATE = 0.0002
BATCH_SIZE = 2
TRAINING_TYPE = 'lora'


def main():
    print(f"[unsloth] Loading model {MODEL_NAME} (4bit={LOAD_IN_4BIT})...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=LOAD_IN_4BIT,
    )

    if TRAINING_TYPE == "lora":
        model = FastLanguageModel.get_peft_model(
            model,
            r=LORA_R,
            target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
            lora_alpha=LORA_ALPHA,
            lora_dropout=0,
            bias="none",
            use_gradient_checkpointing="unsloth",
            random_state=3407,
            use_rslora=False,
            loftq_config=None,
        )

    print(f"[unsloth] Loading dataset from {DATASET_PATH}...")
    raw = json.loads(open(DATASET_PATH, encoding="utf-8").read())
    dataset = Dataset.from_list(raw)
    print(f"[unsloth] Dataset size: {len(dataset)}")

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        args=SFTConfig(
            per_device_train_batch_size=BATCH_SIZE,
            gradient_accumulation_steps=4,
            num_train_epochs=NUM_EPOCHS,
            warmup_ratio=0.03,
            learning_rate=LEARNING_RATE,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            seed=3407,
            output_dir=OUTPUT_DIR,
            report_to="none",
        ),
    )
    print("[unsloth] Starting training...")
    trainer.train()
    print(f"[unsloth] Saving model to {OUTPUT_DIR}...")
    model.save_pretrained(OUTPUT_DIR)
    tokenizer.save_pretrained(OUTPUT_DIR)
    print("[unsloth] Done.")


if __name__ == "__main__":
    main()
